//
// API ENDPOINT DOCUMENTS
//

// SKAPA DOCUMENT
GET http://localhost:3000/documents

###

// SKAPA DOCUMENT
POST http://localhost:3000/documents
Content-Type: application/json

{ 
  "title": "Låtlista 231218",
  "content": "Vestibulum purus nec",
  "userId": "2"
}

###

// ÄNDRA DOCUMENT
PATCH http://localhost:3000/documents
Content-Type: application/json

{ 
  "title": "Låtidén 231224_ny",
  "content": "Ändrad Vestibulum facilisis purus nec",
  "documentId": "2"
}

###

// DELETE DOCUMENT
DELETE http://localhost:3000/documents
Content-Type: application/json

{ 
  "documentId": "2"
}

###